services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  rabbitmq:
    image: 'rabbitmq:3.12.7-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=rabbitmq'
      - 'RABBITMQ_DEFAULT_USER=rabbitmq'
      - 'RABBITMQ_PORT=5672'
    ports:
      - '5672:5672'
      - '15672:15672'
